### ISSUE TITLE
Implementera en lösning för att lägga till och ta bort saldo i "Inventory"-fönstret

### ISSUE THREAD

**Issue by FelixDryselius** [FelixDryselius/1337-Juicifer#70]
## Situationen just nu:
- Genom en vue.component så visas alla ingredienserna och tillhörande information i en lista i "inventory"-fönstret  
- Det finns ingen möjlighet till att ändra saldot just nu.

## Vad som måste göras:
- Lösningen ligger nog i att förstå sig på och implementera "transactions.csv". 
  - Det är här saldot läses in enligt den kod som har givits av Mikael.
  - När "ingredients" används av oss har redan information lästs in och kombinerats från "transactions.csv" så det enda som måste göras är att ändra transactions direkt så uppdateras allt tror jag. 
  - I "app.js" så finns det en del där "transactions" skrivs om. Kolla på det för inspiration

**Comment by ghost** [comment]
Just nu har jag gjort en input som är kopplad till sumbit-knappen. Nästa steg är att implementera det, ska imorgon kolla på de tipsen du lade upp!
